Page({
    data:{
        WeekMovieList:[
            {
                name:"日出",
                comment:"一部看日出的电影",
                imagePath:"/images/movie1.png",
                recommend:true
            },
            {
                name:"夜晚",
                comment:"一部看夜晚的电影",
                imagePath:"/images/movie2.png",
                recommend:false
            },
            {
                name:"大山",
                comment:"一部看大山的电影",
                imagePath:"/images/movie3.png",
                recommend:false
            },
            {
                name:"黄昏",
                comment:"一部看黄昏的电影",
                imagePath:"/images/movie4.jpg",
                recommend:false
            },
        ],
        count:0
    },
    onLoad(){
    }
})